AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  portfolio-backend

  Sample SAM Template for portfolio-backend

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  AjayPatelApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Domain:
        DomainName: ajaypatel.live
        CertificateArn: arn:aws:acm:us-east-1:949638458026:certificate/ac7e8ff9-32f5-4e23-bafb-ce53c76dd6f2
        EndpointConfiguration: EDGE
        Route53:
          HostedZoneId: Z0502293H5TZC2PJ9FFH
      Cors:
        AllowMethods: "'POST,OPTIONS'"
        AllowOrigin: "'https://ajaypatel.live'"
        AllowHeaders: "'Content-Type'"

  AjayPatelFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: sendEmail/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /api/v1/sendEmail
            Method: POST
            RestApiId:
              Ref: AjayPatelApiGateway
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"
      Environment:
        Variables:
          PARAM1: VALUE

Outputs:
  ApiGatewayDomainName:
    Description: "Custom domain name"
    Value: !Ref AjayPatelApiGateway.DomainName
